#!/usr/bin/env bash
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
source "$HERE/profiles/current.env"
source "$HERE/.env.example"
CONFIG=${RECIPE_CONFIG:-"$HERE/.env"}
[[ ! -f "$CONFIG" ]] || source "$CONFIG"
export RECIPE_PROFILE="${RECIPE_PROFILE:-native-mtp-k2}"
case "$RECIPE_PROFILE" in
  native-mtp-k2) export RECIPE_SERVE_ARGS="$HERE/profiles/serve-args.json" ;;
  dspark-k3)
    source "$HERE/profiles/dspark-k3.env"
    export RECIPE_SERVE_ARGS="$HERE/profiles/dspark-k3-args.json"
    ;;
  *) echo 'RECIPE_PROFILE must be native-mtp-k2 or dspark-k3' >&2; exit 1 ;;
esac
export RECIPE_ROOT="$HERE" DRY=${DRY:-0}
export RECIPE_HOSTS="${HOSTS[*]}" RECIPE_IPS="${IPS[*]}"
export RECIPE_IMAGES="${IMAGES[*]:-}"
export FABRIC_IFACE IB_HCA MODEL_DIR DRAFT_DIR NCCL_HOST_DIR OVERLAY_REMOTE IMAGE NCCL_SHA256
export RECIPE_PERSISTENT_CACHE PERSISTENT_CACHE_DIR
export GLM_SKIP_MLA_PLAN GLM_SKIP_MLA_PLAN_AB_INIT VLLM_SERVER_DEV_MODE
export GLM_PREFILL_CHUNK_ADAPTIVE GLM_PREFILL_CHUNK_THRESHOLD
export GLM_ATTN_WEIGHTS=${GLM_ATTN_WEIGHTS:-int8}
export GLM_ATTN_NVFP4_DIR
export GLM_FP4_RECENT_WINDOW=${GLM_FP4_RECENT_WINDOW:-0}
export GLM_FP4_RECENT_AB=${GLM_FP4_RECENT_AB:-0}
[[ -z ${GLM_FP4_RECENT_INIT+x} ]] || export GLM_FP4_RECENT_INIT
export GLM_NVFP4_GROUPS GLM_NVFP4_MORE_DIR
export GLM_LOADER GLM_COALESCED_BATCH_MB GLM_COALESCED_OWNED_MB GLM_COALESCED_THREADS GLM_COALESCED_DIRECT GLM_COALESCED_EMERGENCY_MB GLM_COALESCED_MARGIN_MB GLM_PARAM_HASH
export RECIPE_DISPRAM=${RECIPE_DISPRAM:-0} DISPRAM_HOME=${DISPRAM_HOME:-/srv/glm/dispram}
export RECIPE_KV_HEAD_BYTES RECIPE_PAGE_CACHE_POLICY
export RECIPE_BOOT_PREFLIGHT RECIPE_BOOT_PREFLIGHT_HEADERS RECIPE_BOOT_PREFLIGHT_IMAGE
exec python3 "$HERE/scripts/cluster.py" "$@"
